on:
  workflow_run:
    workflows: ['Code quality']
    branches: ['master']
    types:
      - completed
name: Release - production
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: Production
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'master'
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci && cd src/api/http && npm ci && cd .. && cd websocket && npm ci
      - name: Build
        run: npm run build
        env:
          VITE_APP_NAME: 'Activity timer'
          VITE_APP_KEY: ${{ secrets.ACT_APP_KEY }}
          VITE_API_HOST: ${{ secrets.ACT_API_HOST }}
          VITE_WEBSOCKET: ${{ secrets.ACT_WEBSOCKET }}
          VITE_OPTRO_API_KEY: ${{ secrets.ACT_OPTRO_API_KEY }}
          VITE_POWERUP_ID: ${{ secrets.ACT_POWERUP_ID }}
          VITE_SENTRY_DSN: ${{ secrets.ACT_SENTRY_DSN }}
          VITE_APP_ORIGIN: ${{ secrets.ACT_APP_ORIGIN }}
          VITE_MAILCHIMP_LINK: ${{ secrets.ACT_MAILCHIMP_LINK }}
      - name: cdk deploy
        env:
          ACT_ENV: 'prod'
          AWS_ACCESS_KEY_ID: ${{ secrets.V2_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.V2_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-1'
          TRELLO_SECRET: ${{ secrets.ACT_TRELLO_SECRET }}
        run: cd infrastructure && npm ci && npx cdk bootstrap && npx cdk deploy --require-approval never
